using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;


 [RealtimeModel]
    public partial class ScrollViewModel
    {
        [RealtimeProperty(1, true, true)]
        private Vector2 _scrollview;
    }

/* ----- Begin Normal Autogenerated Code ----- */
public partial class ScrollViewModel : RealtimeModel {
    public UnityEngine.Vector2 scrollview {
        get {
            return _scrollviewProperty.value;
        }
        set {
            if (_scrollviewProperty.value == value) return;
            _scrollviewProperty.value = value;
            InvalidateReliableLength();
            FireScrollviewDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(ScrollViewModel model, T value);
    public event PropertyChangedHandler<UnityEngine.Vector2> scrollviewDidChange;
    
    public enum PropertyID : uint {
        Scrollview = 1,
    }
    
    #region Properties
    
    private ReliableProperty<UnityEngine.Vector2> _scrollviewProperty;
    
    #endregion
    
    public ScrollViewModel() : base(null) {
        _scrollviewProperty = new ReliableProperty<UnityEngine.Vector2>(1, _scrollview);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _scrollviewProperty.UnsubscribeCallback();
    }
    
    private void FireScrollviewDidChange(UnityEngine.Vector2 value) {
        try {
            scrollviewDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _scrollviewProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _scrollviewProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Scrollview: {
                    changed = _scrollviewProperty.Read(stream, context);
                    if (changed) FireScrollviewDidChange(scrollview);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _scrollview = scrollview;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
