using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class BatteriesModel
{
    [RealtimeProperty(1, true, true)]
    private bool _vis;

}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class BatteriesModel : RealtimeModel {
    public bool vis {
        get {
            return _visProperty.value;
        }
        set {
            if (_visProperty.value == value) return;
            _visProperty.value = value;
            InvalidateReliableLength();
            FireVisDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(BatteriesModel model, T value);
    public event PropertyChangedHandler<bool> visDidChange;
    
    public enum PropertyID : uint {
        Vis = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _visProperty;
    
    #endregion
    
    public BatteriesModel() : base(null) {
        _visProperty = new ReliableProperty<bool>(1, _vis);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _visProperty.UnsubscribeCallback();
    }
    
    private void FireVisDidChange(bool value) {
        try {
            visDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _visProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _visProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Vis: {
                    changed = _visProperty.Read(stream, context);
                    if (changed) FireVisDidChange(vis);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _vis = vis;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
