using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class PowerReceiverModel 
{
    [RealtimeProperty(1, true, true)]
    private int _powerCount;


}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class PowerReceiverModel : RealtimeModel {
    public int powerCount {
        get {
            return _powerCountProperty.value;
        }
        set {
            if (_powerCountProperty.value == value) return;
            _powerCountProperty.value = value;
            InvalidateReliableLength();
            FirePowerCountDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(PowerReceiverModel model, T value);
    public event PropertyChangedHandler<int> powerCountDidChange;
    
    public enum PropertyID : uint {
        PowerCount = 1,
    }
    
    #region Properties
    
    private ReliableProperty<int> _powerCountProperty;
    
    #endregion
    
    public PowerReceiverModel() : base(null) {
        _powerCountProperty = new ReliableProperty<int>(1, _powerCount);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _powerCountProperty.UnsubscribeCallback();
    }
    
    private void FirePowerCountDidChange(int value) {
        try {
            powerCountDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _powerCountProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _powerCountProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.PowerCount: {
                    changed = _powerCountProperty.Read(stream, context);
                    if (changed) FirePowerCountDidChange(powerCount);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _powerCount = powerCount;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
